### ISSUE TITLE
[Question] Will `start_managing_pool` be called redundantly N times?

### ISSUE THREAD

**Issue by Restioson** [cunarist/tokio-with-wasm#1]
From what I'm seeing here in `spawn_blocking`
https://github.com/cunarist/tokio-with-wasm/blob/796872768ff76ac7d5f398395bb614e5c8c04493/src/tokio_wasm/task/mod.rs#L186-L200
It seems as though this `start_managing_pool` function 
https://github.com/cunarist/tokio-with-wasm/blob/796872768ff76ac7d5f398395bb614e5c8c04493/src/tokio_wasm/task/pool.rs#L303-L316

will be called as many times as `spawn_blocking` is, whereas from what I can see, only one should be needed.

Is this true or am I misunderstanding?

**Comment by temeddix** [comment]
Hi @Restioson , thanks for your insight :)

Yeah, it looks like that might cause excessive calls. The library *does* work because that's must a management function, but I do admit that it can cause slowdowns.

This should be fixed, though I'm a bit busy these days to do that.

May I ask you if you've experienced significant performance issues?

**Comment by temeddix** [comment]
This should be fixed now, thank you very much for your report :) Feel free to come back for any other discussions!
