### ISSUE TITLE
support target bundler?

### ISSUE THREAD

**Issue by RCasatta** [cunarist/tokio-with-wasm#9]
I've hit:

```
[INFO]: ⬇️  Installing wasm-bindgen...
error: failed to generate bindings for import of `__wbindgen_placeholder__::__wbindgen_module`

Caused by:
    `wasm_bindgen::module` is currently only supported with `--target no-modules` and `--target web`
```

I've read in the readme it's expected but maybe support can be added

**Comment by temeddix** [comment]
Hi @RCasatta , thanks for your participation :)

Currently everything is oriented toward `web` target. This is because `no-modules` is considered old from `wasm-bindgen`.

- https://rustwasm.github.io/wasm-bindgen/examples/without-a-bundler.html#using-the-older---target-no-modules

Therefore, I would recommend you to use the `web` target somehow if possible.

If you still need to use `no-modules`, please leave a PR with `target-no-modules` feature. [this commit](https://github.com/cunarist/tokio-with-wasm/commit/fee36e640cfdc8e2c1ae222aa91c3cfe0a3cd1c9) might be able to help you.
